### ISSUE TITLE
YML project/tool configuration

### ISSUE THREAD

**Issue by deanturpin** [deanturpin/swob#12]
```yml
Dean_laptop: 
        kali: 2018.2 
        gcc: 8 
        clang: 6 
        C++: 14 
        kernel: 4.15 
        python: 3.5.3 
        Firefox: 53.7.3 
        bash: 4.4

```
